version: '3.8'

services:
  nginx:
    build: "./nginx"
    container_name: nginx-container
    networks:
      - db-net
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - "./www/html/:/var/www/html/"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    depends_on:
      - php

  php:
    build: "./php"
    image: php:8.0-fpm
    networks:
      - db-net
    container_name: php-container
    expose:
      - 9000
    volumes:
      - "./www/html/:/var/www/html/"
    depends_on:
      - mysql

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - db-net
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: "0.0.0.0"
    volumes:
      - "/var/lib/mysql"
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php-myadmin
    networks:
      - db-net
    ports:
      - "8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      PMA_HOST: mysql
    depends_on:
      - mysql

networks:
     db-net: